version: '3'

services:

  city-service:
    image: city-service:0.0.1-SNAPSHOT
    restart: always
    environment:
      CITIZEN_URL: "http://city-service:8080"

    ports:
      - "8081:8080"

  citizen-service:
    image: citizen-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "8082:8080"

  city-management-gateway:
    image: city-management-gateway:0.0.1-SNAPSHOT
    restart: always
    environment:
      CITY_URL: "http://city-service:8080"
      CITIZEN_URL: "http://citizen-service:8080"
      GATEWAY_HOST: "http://city-management-gateway:8080"
    ports:
      - "8083:8080"

  city-management-frontend:
    image: city-management-frontend:0.0.1-SNAPSHOT
    restart: always
    environment:
      API_URL: http://city-management-gateway:8080
    ports:
      - "8087:80"
