server:
  port: 8083

isa:
  gateway:
    host: http://localhost:8083

  city:
    url: http://localhost:8080
  citizen:
    url: http://localhost:8081


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"

