server:
  port: 8083

isa:
  gateway:
    host: http://city-management-gateway:8083  # Update to use the service name

  city:
    url: http://city-service:8080  # Update to use the service name
  citizen:
    url: http://citizen-service:8080  # Update to use the service name

spring:
  cloud:
    gateway:
      routes:
        - id: cors_route
          uri: http://localhost:8087
          predicates:
            - Path=/service/**
          filters:
            - RemoveRequestHeader=Host
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 30
