server:
  port: 8083

isa:
  gateway:
    host: http://localhost:8083

  city:
    url: http://localhost:8080
  citizen:
    url: http://localhost:8081

spring:
  application:
    name: city-management-gateway
  cloud:
    gateway:
      routes:
        - id: cors_route
          uri: http://localhost:8087
          predicates:
            - Path=/service/**
          filters:
            - RemoveRequestHeader=Host
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 30
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka
  instance:
    appname: ${spring.application.name}
    instance-id: ${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2


