server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:city
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

isa:
  city:
    url: https://localhost:8081
    url.delete: city/{id}
    url.put: city/{id}
    url.post: city